### ISSUE TITLE
Open apk/wfz from Opera's downloads

### ISSUE THREAD

**Issue by paraflu** [AmazMod/AmazMod#534] opened 2019-04-24 08:21 UTC
If I select an apk or wfz from download window of opera I get this error "invalid file format"

```
04-24 10:13:59.638   564   564 I sensors.qcom: type=1400 audit(0.0:16135): avc: denied { write } for scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=socket permissive=1
04-24 10:13:59.659  2089  2101 I ndroid.systemu: NativeAlloc concurrent copying GC freed 9595(475KB) AllocSpace objects, 0(0B) LOS objects, 62% free, 7MB/19MB, paused 205us total 114.893ms
04-24 10:13:59.719 22774 22774 D FileOpenerActivity: FileOpenerActivity onCreate action: android.intent.action.VIEW scheme: content uri: content://com.opera.browser.DownloadProvider/storage/emulated/0/Download/LikeAppleRedminsrlibverge-1.apk?mt=application%2Fvnd.android.package-archive
04-24 10:13:59.726 22774 22774 D FileOpenerActivity: FileOpenerActivity onCreate result: invalid_file filePath: null
04-24 10:13:59.726 22774 22774 D FileOpenerActivity: FileOpenerActivity showResult result: invalid_file workDir: /data/user/0/com.edotassi.amazmod/cache/workdir
```

After this error I can't install anymore. If I reboot the phone and select the same apk or wfz from filemanager (not from opera) the installation work fine.

From debug I've seen that then ContentResolvere.query fail and return null.

I've tried the playstore version (beta version) and also the compiled version from dev branch.

The solution atm is to avoid download window of opera :)

**Comment by GreatApo** [comment] 2019-04-24 09:55
It is probably caused from the parameters in the URL string ("?" and after).

It should be fixed, at least not to crash the whole install feature.

**Comment by paraflu** [comment] 2019-04-24 10:47
Maybe split with ? as separator? The strange thing it the crash of the sequential call. I don't know the Android framework but I've see in doc that's a framework class so it's strange this behavior. I'll try to fix the method.

If it work you'll see a PR 😏

**Comment by paraflu** [comment] 2019-04-24 12:41
Removing "?.*$" from the uri show a news issue. 

This is the code
```java
    private Uri normalizeUri(Uri uri) {
        String uriString = uri.toString();

        uriString = uriString.replaceAll("\\?.*$", "");
        return Uri.parse(uriString);
    }
```

The conseguent `resolver.query` throw an SecurityException

```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.edotassi.amazmod/com.edotassi.amazmod.ui.FileOpenerActivity}: java.lang.SecurityException: Permission Denial: reading com.opera.android.downloads.DownloadProvider uri content://com.opera.browser.DownloadProvider/storage/emulated/0/Download/LikeAppleRedminsrlibverge-1.apk from pid=12904, uid=10283 requires the provider be exported, or grantUriPermission()
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2952)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3087)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6734)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by GreatApo** [comment] 2019-04-24 16:47
I mean that Amazmod probably doesn't recognize the file as an APK if the code just looks at the end of the location for the file extension.

The problem is not "?", it's the parameters passed after that:
? <- means that parameters are after this point
mt=application%2Fvnd.android.package-archive <- assigns a value to the parameter "mt"

Removing "?" will just break the URL and that probably causes the error, or, those parameters are needed to access the file, I don't know how it works.

**Comment by GreatApo** [comment] 2019-04-25 19:50
I tested and fixed opera mini, commit: fdd4ca236bc7ef5be09f81f72c7df7c7f63241ed

I didn't got the exact logs you provide, hence, you may still get an error.

**Comment by fcaronte** [comment] 2019-04-30 21:23
i can confirm that with new commit is not work too.
![image](https://user-images.githubusercontent.com/26366403/56994312-ffac5680-6b9e-11e9-9e23-b56b24ccc995.png)

**Comment by 1immortal** [comment] 2019-05-14 14:16
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs](https://trello.com/c/9ugXmoGc/1-bugs)

**Comment by 1immortal** [comment] 2019-05-15 05:17
![](https://github.trello.services/images/mini-trello-icon.png) [Open apk/wfz from Opera's downloads](https://trello.com/c/nSSKvLH4/35-open-apk-wfz-from-operas-downloads)

**Comment by paraflu** [comment] 2019-05-15 12:43
well I can't see in trello, maybe access denied.

**Comment by lfom** [comment] 2019-06-30 17:47
@paraflu  did you give AmazMod access to storage? Still having issue with latest dev builds? If yes, please update the logcat info.

**Comment by lfom** [comment] 2019-07-11 21:37
Closing, please reopen if there are new issues, providing more data.

**Closed by lfom** 2019-07-11 21:37 UTC
Labels: already fixed/improved, bug
