### ISSUE TITLE
Stratos 3 AmazMod not work

### ISSUE THREAD

**Issue by malcerz** [AmazMod/AmazMod#736] opened 2019-11-15 19:12 UTC
Stratos 3 (A1929) - AmazMod installs without problems but does not work. There is no widget in the watch, the phone does not detect the service.

**Comment by malcerz** [comment] 2019-11-16 07:01
Overnight the service started and the watch connected to the phone. The backlight brightness setting works.
Not work: File Explorer, Screenshot and (probably) notifications

**Comment by fcaronte** [comment] 2019-11-17 10:15
You can try notification using an app like "fake notification" and about APK install? Maybe new watch have a closed ADB connection and so most things using ADB aren't work correctly

**Comment by uentity** [comment] 2019-11-17 12:33
I own stratos 3 and service works fine. Notifications working, file manager also works.

**Comment by uentity** [comment] 2019-11-17 12:34
But when a new version (218) is going to be released? =)

**Comment by GreatApo** [comment] 2019-11-17 19:51
> But when a new version (218) is going to be released? =)

Try the bleeding edge, it is stable and it will be the next release.

**Comment by malcerz** [comment] 2019-11-18 06:37
In fact, after a few hours everything started, including notifications and file manager.

**Comment by uentity** [comment] 2019-11-18 17:59
@GreatApo thanks for info!
But I was thinking that bleeding edge is with debug enabled, is it?

**Comment by GreatApo** [comment] 2019-11-18 20:57
> @GreatApo thanks for info!
> But I was thinking that bleeding edge is with debug enabled, is it?

That is correct :)

**Comment by uentity** [comment] 2019-11-19 06:14
Bleeding edge works fine so far.
The only issue I faced is a little bit 'clumsy' widgets reordering from mobile app.

**Comment by fcaronte** [comment] 2019-11-19 06:18
Yes we have little problem with drag and drop rearrangement but for now we are test if new widget system work correctly and keep widget enabled as we want

**Comment by bigata** [comment] 2019-11-19 11:42
I have been testing for some days the last release (not Edge), and almost everything seems to work (haven't tried calendar sync/widget). 

I have found some things that may fail sometimes, listed below:  

- Considerable battery drain (from 5 days without Amazmod, with continuous heartrate and connectivity) to less than 2 days with Amazmod installed, sometimes with a 50% usage in 10h. This is what has most impact I think.  
- Stratos 3 launcher gets restarted and it doesn't display installed apps, so Amazmod can only be accessed by its Widget
- Sometimes, notifications doesn't arrive or arrive with big delays. 
- Sometimes, answers from the watch are not sent (f.e. Whatsapp or Telegram), even with the app running on the phone and all battery settings off.

**Comment by fcaronte** [comment] 2019-11-19 11:44
> I have been testing for some days the last release (not Edge), and almost everything seems to work (haven't tried calendar sync/widget).
> 
> I have found some things that may fail sometimes, listed below:
> 
> * Considerable battery drain (from 5 days without Amazmod, with continuous heartrate and connectivity) to less than 2 days with Amazmod installed, sometimes with a 50% usage in 10h. This is what has most impact I think.
> * Stratos 3 launcher gets restarted and it doesn't display installed apps, so Amazmod can only be accessed by its Widget
> * Sometimes, notifications doesn't arrive or arrive with big delays.
> * Sometimes, answers from the watch are not sent (f.e. Whatsapp or Telegram), even with the app running on the phone and all battery settings off.

Please, if you can, try to install blending edge version to confirms battery problems and other thing's.

**Comment by uentity** [comment] 2019-11-19 18:38
I installed bleeding edge, used it for 24 hours and I can confirm considerable battery drain (40 - 50%).

Also other issues listed by @bigata also present, except that messages delivery seems more consistent. But tis may be an effect of recently updated firmware that raised overall device smoothness, so it's hard to tell.

**Comment by bigata** [comment] 2019-11-20 09:23
Tried Bleeding Edge with the same impact on battery, as said by **uentity**, notifications seem arriving better, but still this battery drain is quite considerable. I read that Stratos 3 Amazfit OS is based in another version of Android? If so, maybe the slept features doesn't work properly.

**Comment by fcaronte** [comment] 2019-11-20 09:36
Thanks for the battery problem confirmation, probably we can check better if and when we will have a stratos 3 to try. At maybe try to take and put here some log from Amazmod app to check if can help

**Comment by uentity** [comment] 2019-11-20 16:00
With latest bleeding edge build released yesterday phone app no longer connects to watches.
Did reboot and reinstalled both service and phone app - no luck.

**Comment by fcaronte** [comment] 2019-11-20 16:40
On Yesterday release do only small change on app esthetic so nothing change
on connection. Try to force kill amazfit app and then Amazmod and try to
connect again

Il mer 20 nov 2019, 17:00 Alexander Gagarin <notifications@github.com> ha
scritto:

**Comment by uentity** [comment] 2019-11-20 19:06
@fcaronte something broken and even earlier stable release did not connect.
I was able to fix it by manually restarting service on watches via `adb`.

**Comment by uentity** [comment] 2019-11-22 02:30
One more issue with current bleeding edge is that heart rate diagram isn't shown inside phone app.

**Comment by kvegeta** [comment] 2019-11-26 13:49
I have tried to installa AmazMod but no widget or app on the smartwatch (stratos 3) and amazMod on the smartwatch doesn't obviously see it...
I have used Amazmod.Service.Installer.ver.1904

**Comment by fcaronte** [comment] 2019-11-26 13:57
> I have tried to installa AmazMod but no widget or app on the smartwatch (stratos 3) and amazMod on the smartwatch doesn't obviously see it...
> I have used Amazmod.Service.Installer.ver.1904

Try reboot watch and if not fix go to last page open Amazmod and go to widget reorder end enable Amazmod widget

**Comment by kvegeta** [comment] 2019-11-26 14:13
i don't see amazMod in the app list :/

**Comment by fcaronte** [comment] 2019-11-26 14:33
> > Try reboot watch and if not fix go to last page open Amazmod and go to widget reorder end enable Amazmod widget
> 
> i don't see amazMod in the app list :/

Try to reinstall again, if for other guys work on stratos 3 should work for you too. There are two APK and service is the APK to install on watch

**Comment by kvegeta** [comment] 2019-11-26 14:35
> > > Try reboot watch and if not fix go to last page open Amazmod and go to widget reorder end enable Amazmod widget
> > 
> > 
> > i don't see amazMod in the app list :/
> 
> Try to reinstall again, if for other guys work on stratos 3 should work for you too. There are two APK and service is the APK to install on watch

I fully agree with that, but i have already installed it 2 times with no results :D

**Comment by fcaronte** [comment] 2019-11-26 14:42
Try with edgy version maybe the problem is here https://github.com/AmazMod/AmazMod/releases/tag/edgy

**Comment by uentity** [comment] 2019-11-26 19:03
@kvegeta yes, amazmod widget won't appear in main watches menu. The only way to enable it is via phone app. Then you'll be able to swipe up/down from watchface to find it.

Use bleeding edge.

**Comment by uentity** [comment] 2019-11-26 19:14
BTW I think that notifications delivery problems are caused by Amazfit app in first place.
I noticed that when delivery starves Amazfit also cannot connect to watches normally and update battery status, sync data, etc. After a while, it reconnects and bunch of messages get delivered one after another.

What surprises me is that I own a very first generation Pebble (and Pebble 2 also). This device with tiny battery had ZERO notifications delivery problems from the beginning and lasted for a week.
And now I switched to nice-looking Stratos 3 from 2019 with powerful processor, large battery, lots of sensors, etc, but ugly notifications that can only be fixed by third party app and eats battery in two days. Just crazy.

Thanks again for your work!

**Comment by fcaronte** [comment] 2019-11-26 19:28
probably you need to check all possible battery saver option on your phone for both two app amazfit and amazmod, and yes probably need some adjustment for stratos 3 but as now we haven't a watch to do test

**Comment by uentity** [comment] 2019-11-27 04:57
Battery optimizations are disabled for both Amazfit and Amazmod apps.
Today an update of Amazfit came to my phone. Will see if they have fixed connection issues.

**Comment by kvegeta** [comment] 2019-11-27 17:12
> @kvegeta yes, amazmod widget won't appear in main watches menu. The only way to enable it is via phone app. Then you'll be able to swipe up/down from watchface to find it.
> 
> Use bleeding edge.

Still nothing with last stable installation... i'm going to try to istall bleeding one

**Comment by HokusLokus** [comment] 2019-11-28 20:53
Try after installation from adb shell: adb shell am startservice com.amazmod.service 
Worked for me!

**Comment by HokusLokus** [comment] 2019-11-28 21:00
Then in the Amazmod app, select Settings, Widgets, AmazModService.

**Comment by ravensergio** [comment] 2019-12-03 23:27
Hi.I am a fresh owner of a Stratos 3. I installed the AmazMod, but sadly the notifications are arriving too late, with a delay as high as 30 seconds behind the phone, even if the widget is present. Also,  idk what happens with the app drawer, when i sideload an apk, i cannot see the watches base apks only the sideloaded ones. But after a restart of the watch, is vice-versa. The AmazMod still shows itself, maybe because is s widget. I hope that these problems will go away after the watch is more mature. Regards.

**Comment by HokusLokus** [comment] 2019-12-04 11:09
Create an empty folder in the main menu of Stratos 3 and name it launcher_config.ini then restart the watch. Now all apk are displayed.

**Comment by fcaronte** [comment] 2019-12-04 11:22
But have you try to use "enable applist" From tweaking menu of Amazmod? It
think it do the same thing and create the file automatically

Il mer 4 dic 2019, 12:09 HokusLokus <notifications@github.com> ha scritto:

**Comment by ravensergio** [comment] 2019-12-04 12:02
>@HokusLokus Create an empty folder in the main menu of Stratos 3 and name it launcher_config.ini then restart the watch. Now all apk are displayed.
I dont have AmazMod anymore, because of delay issues and battery drain that i have with it installed ( i'll wait until the watch will be more popular/bugs fixed), but i tried your solution and it worked! Thank you. Now i have the watch app drawer with all the apks in it, even the system and the custom ones. Thank you ,this is priceless for me.

**Comment by bigata** [comment] 2019-12-19 12:25
Hi, 

I am currently trying again the last version of Bleeding Edge (from 2 days), I will let you know my feelings after a few days, but some things already detected: 
- Battery drain is still there, I made sure Admin Rights are enabled and wifi toggle is off. I expect less than 3 days of battery. 
- A bit of delay in the notifications, not always like as before. (Last Amazfit app, Android 9)
- Answers doesn't always works, at least in WhatsApp
- You cannot navigate Amazmod Service app with Stratos 3 buttons (Ok, up, down and back), and that would be very usefull.

**Comment by fcaronte** [comment] 2019-12-19 13:02
Yes you can try to give as log. As now we don't touch nothing about stratos 3

**Comment by uentity** [comment] 2019-12-19 19:17
I noticed an improvement in notifications delivery in recent builds. But had a bug that same notification can arrive two times and more in a row.

**Comment by fcaronte** [comment] 2019-12-19 19:20
Check and enable "ungroup notification " and see if fix the problem

**Comment by bigata** [comment] 2019-12-23 12:10
Hi, 

After a few days using Bleeding Edge: 
- Notifications seem to be more stable since last Amazfit app update. It takes a bit to arrive but almost all get to the smartwatch in less than 30 seconds. Answers may take longer to be sent. 
- Battery life is affected by it, at most, it lasted 3 days and few hors for me, while with native notifications, the minimum that lasts is 7 days 
- Being able to use Stratos 3 buttons to get up and down the notifications and AmazMod menus would be very usefull. How can we create a feature request?

Last but not least, I am attaching the logs extracted with AmazMod phone app. 

[log_bundle.log.gz](https://github.com/AmazMod/AmazMod/files/3994846/log_bundle.log.gz)
[amazmod.log](https://github.com/AmazMod/AmazMod/files/3994849/amazmod.log)

**Comment by fcaronte** [comment] 2019-12-27 20:16
i can't read watch side log "log_bundle.log.gz" but seem to have a lot of transport problem and maybe we need some new thing from huami lib

**Comment by fcaronte** [comment] 2019-12-28 10:52
> Hi,
> 
> After a few days using Bleeding Edge:
> 
> * Notifications seem to be more stable since last Amazfit app update. It takes a bit to arrive but almost all get to the smartwatch in less than 30 seconds. Answers may take longer to be sent.
> * Battery life is affected by it, at most, it lasted 3 days and few hors for me, while with native notifications, the minimum that lasts is 7 days
> * Being able to use Stratos 3 buttons to get up and down the notifications and AmazMod menus would be very usefull. How can we create a feature request?
> 
> Last but not least, I am attaching the logs extracted with AmazMod phone app.
> 
> [log_bundle.log.gz](https://github.com/AmazMod/AmazMod/files/3994846/log_bundle.log.gz)
> [amazmod.log](https://github.com/AmazMod/AmazMod/files/3994849/amazmod.log)

can you try to disable battery chart, heart rate chart and all sent data setting on greatfit/calendar menu?? i would to see if using only notification give same transport error and battery problem

**Comment by fcaronte** [comment] 2019-12-28 11:15
> I noticed an improvement in notifications delivery in recent builds. But had a bug that same notification can arrive two times and more in a row.

this happen to me one time too with 4time same message and i fix reboot both phone and watch

**Comment by icepower03** [comment] 2020-01-26 19:51
same Pb with stratos 3 all brand new.

tried with windows service or with one 'tool all in one', all is success, the watch reboots , but the mazmod menu never appears.

is there a pb with recent models?

**Comment by fcaronte** [comment] 2020-01-26 20:08
> Hello,
> same Pb with stratos 3 all brand new.
> 
> tried with windows service or with one 'tool all in one', all is success, the watch reboots , but the mazmod menu never appears.
> 
> is there a pb with recent models?
For Stratos 3 you need to unlock applist as on the first firmware of old pace\stratos. Check on xda how to do that

**Comment by GreatApo** [comment] 2020-01-28 00:43
Unfortunately debugging Stratos 3 will require us to have some **dev units to test**. We have already gathered the money for one unit and we are trying to get to a second one to make an order.

If anyone wants to contribute to the project, you can do so at our [open collective page](https://opencollective.com/amazmod-33).

**Comment by SelcouthGuy** [comment] 2020-03-02 13:44
Hello guys. Where we are with stratos 3 bugs? (Asking ppl with watch)
I'm mostly interested this damn battery drain issue. Is something better or we need to wait little more?
Thank you in advance for the response. :smiley:

**Comment by GreatApo** [comment] 2020-03-03 01:48
We are waiting for the dev units. No fixes have been committed for Stratos 3. The watch is still "unsupported".

**Comment by GreatApo** [comment] 2020-04-27 19:44
Last build works with Stratos 3. Personally I face connection problems (phone takes too much time to send data) but it generally works. Weather provider works and we are constantly making UI fixes and improvements. This issue will close. If you face any problem with the last build, open a new issue describing the issue.

**Closed by GreatApo** 2020-04-27 19:44 UTC
Labels: bug
