### ISSUE TITLE
Amazmod crashing while incoming call

### ISSUE THREAD

**Issue by 4eGuevara** [AmazMod/AmazMod#504] opened 2019-04-17 13:12 UTC
When I'm receiving incoming call service crashed. Notification from CallUI, Phone app etc. disabled. Disabling call notification from messengers in phone app helped to solve this issue, but after that I can't reject or accept call. My watch - Huami Amazfit Verge, service-1891

**Comment by GreatApo** [comment] 2019-04-17 14:20
Unfortunate I will close this issue as duplicate. The relevant issue it the following:
https://github.com/AmazMod/AmazMod/issues/400

Your comment is not linked in that issue. For your information, the crashes have been fixed/avoided however this feature is still buggy and need to be fixed.

**Comment by 4eGuevara** [comment] 2019-04-17 14:27
I don't think that this is duplicate, cause for me it's crashed while I'm getting mobile call, not messenger call. But really helps disabling call notification from messengers! But after that, as I told, I can't reject or accept MOBILE call, not messenger call!

**Comment by GreatApo** [comment] 2019-04-17 14:36
That is odd. The thing is that phone calls are not handled by Amazmod but from Amazfit app directly.

I will leave this open then however it seems to be completely related to app calls.

Additionally, it would be useful if you tested the current dev versions because of the small fix I mentioned. I have compiled the phone app and service for you [here](https://we.tl/t-B92VqzyTrE) (7 days link). Mind that you wont be able to get OTA with this versions (different signature) and you will have to uninstall both phone/service apps before installing and if you want to get the officially released versions. Changes are listed in changelog.

**Comment by 4eGuevara** [comment] 2019-04-17 15:40
Ok, I have installed this version. Now testing.... Thx

**Comment by 4eGuevara** [comment] 2019-04-17 16:02
Hmmm, for now (I received 5 incoming calls) everything is fine. But I noticed one strange thing - I cant reject hidden calls (if number is hidden) and I think that this bug is Firmware bug and previous crashed amazmod service was exactly after such calls, but I'm not sure. I need more time to test. I'll tell you later. Anyway - thanks for fast help)

**Comment by GreatApo** [comment] 2019-04-17 16:09
So it seems that the problem is indeed related. The bug you mentioned is definitely connected to Amazfit and not Amazmod (as I mentioned earlier).

I am closing this issue because of the connection with the other one open. Feel free to comment again if you feel it needs to be re-opened.

**Closed by GreatApo** 2019-04-17 16:09 UTC
Labels: evaluating

**Comment by 4eGuevara** [comment] 2019-04-18 07:54
I got almost 20 calls and everything is fine - no crashes. This version awesome! Thx for help!
