### ISSUE TITLE
Notification message multilang issue

### ISSUE THREAD

**Issue by mplx** [AmazMod/AmazMod#748] opened 2019-11-22 21:05 UTC
My Android OS is set to german language, while I'm using AmazMod in English (`Settings` > `Choose Language` > `English`). Thus I`m expecting notifications from AmazMod also to be in english language.

However, the message that an clock is connected is in German (OS language) while others like `battery fully charged` are in English (app language). See screenshot below.

![screenshot2](https://user-images.githubusercontent.com/1986588/69459439-059f9a00-0d72-11ea-80bc-c7a30c3b3639.jpg)

`Amazfit Verge war verbunden`

1.) The message should be in the selected language which might differ from OS.

2.) The german message is incorrect. `war verbunden` means `was connected (but isn't anymore)` so it should be better somelink like `is connected` (`Amazfit Verge ist verbunden`) as the message is present all the time a clock connection is established. In Crowdin the only matching string I found is `was connected` which is **literally translated correctly** to `war verbunden` but depending on the context (`device_connected`) the german notification is not correctly used (in this context the crowdin translate suggestion `wurde verbunden` is much better in terms of `the connection has been established` but I would prefer to express that an active connection is still there, thus `ist verbunden`). However, can we correct the literal translation, or is this problematic as the string could be used somewhere else where the literal translation *is* correct? While it might be not a big deal itself *this one* is the one and only message an AmazMod user is seeing (or has to see) each time he/she uses the mobile in any context so it really should be correct. *(In the end it's related to platforms like Crowdin where you have to translate strings literally without knowing where and how it's used in the software... here something like `Verbindung zu Amazfit aktiv` (connection active) or `Verbindung zu Amazfit hergestellt` (connection established) would be more practicable/catchy.)*

**Comment by fcaronte** [comment] 2019-11-22 22:03
I try with Italian language and yes notification always use phone language (I put Amazmod to English) I see the low battery level and Amazmod connect with Italian phone language. I don't think you can force to use non system language but I'm not 100% sure. About connection message usually I hide this notification but yes seem to show always "watch model" is connected and I don't remember if was a wanted thing or a bug but I will try to check.
About your full charge notification I think simple German string miss this translation

**Comment by fcaronte** [comment] 2019-11-22 22:06
Ok is not a missing string problem and so need a check 👍

**Comment by fcaronte** [comment] 2019-11-22 22:14
Can you try blending edge version to see if has the same issue?

**Comment by fcaronte** [comment] 2019-11-23 15:55
I can confirm statusbar notification use system languages and you have two different languages because actual playstore version haven't all new string update and as now only dev version (edgy version) is full translated

**Comment by mplx** [comment] 2019-11-24 09:58
I used the 1.1.8 Build 217 from PlayStore Beta. I've installed bleeding edge (1.1.8-dev Build 218; released 17h ago) and waiting for the watch to be fully charged...

**Comment by fcaronte** [comment] 2019-11-24 10:00
Ok you will see a lot more translated part, battery graph and I think all other menu's too

**Comment by mplx** [comment] 2019-11-24 10:59
What I did was to uninstall 1.1.8 Build 217, installed a freshly downloaded bleeding edge released yesterday and rebooted the phone. Then charged the watch. However, it's still the same - charge notification message in english (=APP) and connection notification message in german (=OS/Android 9).

![screenshot3](https://user-images.githubusercontent.com/1986588/69493617-03902500-0eb1-11ea-8f60-ed0f30e2bdcf.jpg)

I set the app language now to autodetect (=german) to see if the next charge message will change.

**Comment by fcaronte** [comment] 2019-11-24 11:06
So in this photo you use Amazmod set to English languages?

**Comment by mplx** [comment] 2019-11-24 11:09
yes

**Comment by mplx** [comment] 2019-11-25 08:21
It does not matter which language is set in the app (on phone) - messages still stay the same.

However, my watch is set to english so maybe the charged message is sent from the watch (OS=english) while the connection message is generated on the phone (OS=german)!?

**Comment by fcaronte** [comment] 2019-11-25 08:36
I do some test yesterday and fix the Always connected status, and about language yes persistent notification I don't know why but use the phone system language and all other notification use correctly Amazmod setting languages

**Comment by fcaronte** [comment] 2019-12-04 23:38
Now should work correctly on last dev/edgy version. If you confirm this we can close this issue

**Closed** 2019-12-27 20:14 UTC
