### ISSUE TITLE
Bug: Connecting / Disconnecting after receiving a notificatik 

### ISSUE THREAD

**Issue by andrewk1993** [AmazMod/AmazMod#311] opened 2018-11-18 06:53 UTC
Okay guys i need help and maybe helps the dev to find a solution to this.

I have the Huawei Mate 10 Lite running EMUI 8. For some reason, frequently, when my phone receives a notification, the amazfit app disconnects and reconnects immediately after a second. So instead of getting the notification from amazmod from the app, i get the connect/disconnect notification on my watch. I have all powersaving options off, ignored optimisations for all apps etc.. 

This happens ONLY with notifications. The watch could be connected to the phone for hours without any interruption (with wifi or data on as well) but a problem would occurs only when you receive that one notification. I dont understand why. This happens as well with all versions of the amazfit app i tried.

However, i have used along with amazmod another service for notifications called AMF. This services does not interrupt or has no issues with with the amazfit app and i can get notifications smoothly on my watch. So AMF works perfectly fine as it sends its own notifications on the watch while having amazmod enabled instead the problem occurs. The same problem occurs if amazmod wasnt installed om my watch and i was depending only on amazfit app! 

Can anyone tell me if they experienced something like that? I dont like AMF, the design of the notifications is not nice but it justs works..

**Comment by lfom** [comment] 2018-11-19 14:42
What watch model and firmware? This happened with me with iOS, when I enabled the built-in (from WOS2) disconnection notification, it works fine on Pace with latest CN firmware and EMUI 8.

**Comment by andrewk1993** [comment] 2018-11-19 16:05
I have the Amazfit Pace
Model A1612 US
ROM version 2.8.1.0
And i have the latest EMUI8

Is there anything i can do about it?

**Comment by lfom** [comment] 2018-11-20 14:10
1. If you have enabled the "far away" notification on watch, disable it;
2. Make sure on phone you have enabled "ignore optimizations" and "manual management" for both stock Amazfit and AmazMod, it has been working fine here for a while.

**Comment by andrewk1993** [comment] 2018-11-20 17:14
Where do i find the far away notification? Ive done everything but i cant find this setting.

**Comment by lfom** [comment] 2018-11-25 01:53
> Where do i find the far away notification? Ive done everything but i cant find this setting.

In AmazMod widget menu, scroll down, you should see Disconnect Alert and Away Alert (<- disable this one).

**Comment by andrewk1993** [comment] 2018-11-25 07:40
Thank you! The settings in amazmod widget are not saved to the watch i guess after some changes. I disable the away alert and when i get back to the widget i find it enabled again. This happened with other settings as well

**Comment by lfom** [comment] 2018-11-25 17:59
> Thank you! The settings in amazmod widget are not saved to the watch i guess after some changes. I disable the away alert and when i get back to the widget i find it enabled again. This happened with other settings as well

Clear service APK's data (adb shell pm clear com.amazmod.service) or uninstall/install again, then sync settings with phone and try again. I haven't had this issue for a long time now, maybe it was fixed in some Amazfit update...

**Comment by lfom** [comment] 2019-01-20 13:14
So it seems that this problem isn't caused by AmazMod but it's an Amazfit/firmware issue. Closing.

**Closed by lfom** 2019-01-20 13:14 UTC
Labels: evaluating, invalid

**Comment by piotrrutk** [comment] 2019-06-20 17:01
andrewk1993 - do you find a solution Bug: Connecting / Disconnecting after receiving a notifications?
I have the same problem.

**Comment by lfom** [comment] 2019-06-20 17:24
> andrewk1993 - do you find a solution Bug: Connecting / Disconnecting after receiving a notifications?
> I have the same problem.

Update to the latest version and enable only custom UI (the ones you can reply to). Next version should make standard UI more stable.

**Comment by piotrrutk** [comment] 2019-06-21 09:01
What custom UI?

I have latest wersion of Amazfit Watch app and official firmware watch ver. 2.3.10.4
