### ISSUE TITLE
No custom UI replies after updating to Android 9.0 Pie

### ISSUE THREAD

**Issue by antares10** [AmazMod/AmazMod#265] opened 2018-10-24 12:47 UTC
Hi!

I have a problem, day before yesterday I updated my phone (Huawei P20 Pro) to android 9, and since then I cannot get the custom notifications to work. I tried to restart both watch and phone, reinstall service and phone app but no success.
The test notification can be sent successfully, but the reply button is not shown (not sure if it is normal behaviour), but when I got messages I can see only the default notifications. The push notifications in the Amazfit app are turned off, only the AmazMod is turned on. 

What could be the problem?

**Comment by diotto** [comment] 2018-10-24 13:18
Hi @antares10 
If the test notification is working it looks like watch and phone are communicating. Have you sent a Custom UI notification, right ? The fact that test notification does not show Reply button it ok, it's normal behavior.
In Main Screen is Amazmod showing the watch as connected ?
Could you also check "Stats > Open Notifications Log" and see if notifications are being caught there ?

**Comment by antares10** [comment] 2018-10-24 14:09
Yes I have sent the Custom UI notification besides the other two and it seems to be okay. 
In the main screen it shows the watch is connected (however after some time it disconnects, it is also an issue for me, but this no custom notification issue is present when it shown as connected).
In the Stats I can see e.g the Gmail notifications twice. One of them has a record with GROUP comment, the other is with CONTINUE, but I can see only the standard notification on my watch.

**Comment by lfom** [comment] 2018-10-24 14:21
@antares10 Do you have the latest service APK on watch? Do you see AmazMod widget on it?

If you have installed any previous version, you may need to check if you have an old version installed, so you have two versions running on watch. This kind of behavior usually means the service isn't running on watch.

**Comment by antares10** [comment] 2018-10-24 14:31
Yes the latest service (1588) is installed. Today I uninstalled (revoked admin before) and then reinstall the service, but no luck. I can see the AmazMod widget on the watch. 
If the service is not running how can I send the test notification and why it is showing as connected?

**Comment by lfom** [comment] 2018-10-24 14:35
well, then I am out of ideas... if you are sure stock Amazfit isn't sending the standard UI notifications, then it's a very specific problem... Can you get a logcat from phone, filtering for "amazmod"?

**Comment by antares10** [comment] 2018-10-24 19:19
Sorry I did not get the logcat from my phone yet, but tried different ways.
I reinstalled and restarted both devices. After I set to not show local notifications. In this case the Gmail does not showed anything on the watch. After I set the app to forward local notifications as well, after this at the first time the watch showed a standard notification, but since then the app cannot connect to the watch. 
I was thinking if maybe the newest sw (2.3.6 stratos) changed something.
Any other ideas based on this?
Thank you!

**Comment by lfom** [comment] 2018-10-25 22:39
StandardUI notifications don't rely on service app, they work if it's not installed at all. My bet is it's something related to the phone...

**Comment by antares10** [comment] 2018-10-31 18:35
@lfom @diotto 
Hello guys!

I have the logcat from the watch, it seems that the service crashes. Can you please check it what could cause it?

10-31 19:34:23.490 879-891/? D/AmazMod: MainService action: incoming_notification
10-31 19:34:23.491 879-891/? D/AmazMod: MainService onDataReceived: com.amazmod.service.events.incoming.IncomingNotificationEvent@382408ed
10-31 19:34:23.525 879-879/? D/AmazMod: MainService incomingNotification: amazmod.com.transport.data.NotificationData@7fc51b3
10-31 19:34:23.553 879-879/? E/AmazMod: DnD lowSDK exception: android.provider.Settings$SettingNotFoundException: zen_mode
10-31 19:34:23.622 879-879/? D/AmazMod: NotificationService notificationSpec.getKey(): 0|com.google.android.gm|-598758214|gig:-635208087:^sq_ig_i_personal|10069
10-31 19:34:23.622 879-879/? D/AmazMod: NotificationService6 notificationSpec.getKey(): 0|com.google.android.gm|-598758214|gig:-635208087:^sq_ig_i_personal|10069
10-31 19:34:23.725 424-705/? I/ActivityManager: START u0 {flg=0x1c080000 cmp=com.amazmod.service/.ui.NotificationActivity (has extras)} from uid 10031 on display 0
10-31 19:34:24.852 879-879/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amazmod.service, PID: 879
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amazmod.service/com.amazmod.service.ui.NotificationActivity}: java.lang.IllegalArgumentException: width and height must be > 0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
        at com.amazmod.service.ui.NotificationActivity.onCreate(NotificationActivity.java:152)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
10-31 19:34:24.912 424-551/? W/ActivityManager:   Force finishing activity 1 com.amazmod.service/.ui.NotificationActivity
10-31 19:34:25.473 424-445/? W/ActivityManager: Activity pause timeout for ActivityRecord{3cf26f75 u0 com.amazmod.service/.ui.NotificationActivity t66 f}
10-31 19:34:25.786 555-555/? I/springboard: [class com.amazmod.service.springboard.AmazModPage] ==> check key: 844970862 , fed : onResume
10-31 19:34:25.786 555-555/? I/springboard: plugin [com.amazmod.service.springboard.AmazModPage] onResume
10-31 19:34:25.815 555-555/? D/AmazMod: WidgetSettings getLong exception: org.json.JSONException: No value for pref_battery_date_last_charge
10-31 19:34:25.815 555-555/? D/AmazMod: AmazModPage updateTimeSinceLastCharge level: 98 / scale: 100 / batteryIconId: 17303143 /  0

**Comment by lfom** [comment] 2018-11-02 22:46
Yes, app fails to get the notification icon and then service crashes because there is no icon...

Does it only happen with Gmail or any app?

**Comment by antares10** [comment] 2018-11-03 07:13
It does happen with every app.

**Comment by lfom** [comment] 2018-11-08 18:11
I have found today that on EMUI 8 there is an option to show numbers or nothing at all at the notification bar, maybe you have a similar setting that is hiding the notification icons? Do you see them at the notification bar when a new on arrives?

**Comment by antares10** [comment] 2018-11-08 18:34
Yes, I know this option and it is set to be able to see the icons in the
notification bar.

**Comment by lfom** [comment] 2018-11-11 08:33
We need to test this with some device or emulator with Pie.

**Comment by Disturbedbcn** [comment] 2019-01-07 17:42
Same problem here. I updated my Honor 10 to Android Pie and the Custom notifications doesn't work.
Reinstalled the service and the same problem. There is any update about this? Thank you.

**Comment by davigar1391** [comment] 2019-02-08 16:41
My case is different, I have a Huawei P20 Pro (Pie Updated) and CustomUI notifications works perfectly, I can reply messages but I want to consult notification history the service force closes. My watch is an Amazfit Stratos with stock 2.3.7.0 version. I tried to format factory the watch and the phone but the problem persists.

I am using 1.1.3 app and 1880 service. Here is a logcat with the problem when I press on the icon of notification history.

[logcat.txt](https://github.com/AmazMod/AmazMod/files/2845952/logcat.txt)

I don't hide the content of the notifications and It shows the icon in my phone. If you need some additional logcat or try some configuration in the phone tell me and try.

Thanks.

**Comment by lfom** [comment] 2019-02-09 21:52
@davigar1391 Thank for the logcat, it seems the error is related to the notification icon.

1. Does it happen with any app that sends notifications to watch?

2. Do you have the option to use avatars in notifications enabled? Either way, could you please try with it set as the other way (disabled if it is enabled now or enabling it otherwise)?

3. When the notification is shown on watch, it displays the icon correctly? Could you please post a screenshot?

**Comment by davigar1391** [comment] 2019-02-09 23:44
> @davigar1391 Thank for the logcat, it seems the error is related to the notification icon.
> 
> 1. Does it happen with any app that sends notifications to watch?
> 2. Do you have the option to use avatars in notifications enabled? Either way, could you please try with it set as the other way (disabled if it is enabled now or enabling it otherwise)?
> 3. When the notification is shown on watch, it displays the icon correctly? Could you please post a screenshot?

1. Yes, I tried with whatsapp, gmail, telegram and it happens with all

2. Yes, I have the option enabled but I try with the option disabled and the service force closes too. 
Here is a logcat opening notification history with the avatars option disabled in amazmod app.
[logcat.txt](https://github.com/AmazMod/AmazMod/files/2848388/logcat.txt)

3. No, the notification doesn't show the icon correctly. It has a circular cutout at the bottom right. 
Here are two screenshots.
![photo_2019-02-10_00-32-23](https://user-images.githubusercontent.com/34111683/52527685-f660cb80-2ccc-11e9-8c60-156db1528204.jpg)
![photo_2019-02-10_00-32-18](https://user-images.githubusercontent.com/34111683/52527686-f660cb80-2ccc-11e9-9442-9f44decc0f1c.jpg)

**Comment by fcaronte** [comment] 2019-02-24 10:11
The black background is for app icons and is strange is not seein
![15510030710078337971451357493558](https://user-images.githubusercontent.com/26366403/53297861-ee547000-3824-11e9-9d7e-8a4b5dfa85b4.jpg)
g

**Comment by diotto** [comment] 2019-02-24 14:17
@davigar1391 do you use black theme in phone? Maybe your default icons (in phone) are already white and the inverted are black

**Comment by davigar1391** [comment] 2019-02-25 15:07
> @davigar1391 do you use black theme in phone? Maybe your default notification icons (in phone) are already white and the inverted are black.
> If yes, can you please (just for testing purpose) switch phone theme to white and check if problem is solved?

It's very strange. My phone have an option to dark interface colors but notifications colors don't change, only other parts of the UI. 

I used this option in Oreo and Amazmod 1880 version and worked perfectly, but with Android Pie using both options (default white theme and the black) causes the service crash and the app icon doesn't appear.

**Comment by diotto** [comment] 2019-02-27 00:55
@davigar1391 I just upgraded my phone to Android Pie and couldn't reproduce your bug. Sorry for not finding it, we'll continue trying to understand why it happens to you.

**Comment by amknipp** [comment] 2019-02-27 01:07
Hi @diotto! Greetings from Brazil! After my Galaxy S9 updated to Android pie the notifications are being delayed. Also the phone app is randomly force closing. Battery drain on both phone and watch are higher than the normal. Have you experienced that?

**Comment by davigar1391** [comment] 2019-03-04 20:53
> @davigar1391 I just upgraded my phone to Android Pie and couldn't reproduce your bug. Sorry for not finding it, we'll continue trying to understand why it happens to you.

Hi @diotto, this is the notification aspect on my mobile phone. Can the problem be related to the icon of the application that appears in color?

![photo_2019-03-04_21-53-45](https://user-images.githubusercontent.com/34111683/53762284-fddc5480-3ec7-11e9-9dea-94d9dc146156.jpg)

**Comment by antares10** [comment] 2019-03-18 12:53
Hi! Are there any news? I have the same problem now as @davigar1391.

**Comment by davigar1391** [comment] 2019-03-24 14:07
With the new update 1.1.5 and the new service service 1889 the problem persist

**Comment by antares10** [comment] 2019-03-26 19:43
Solution is to use:
Drawable drawable = resources.getDrawable(notification.icon);
instead of
Drawable drawable = resources.getDrawable(iconId);
in the NotificationFactory.java in the phone app.

**Comment by fcaronte** [comment] 2019-03-26 20:42
for me only changing this line, nothing change on the telegram icon, is like stock setting and receive custom ui with correctly icon + picture

**Comment by antares10** [comment] 2019-04-10 11:29
@GreatApo I think you can close this issue, it is fixed with the NotificationFactory modification.

**Comment by GreatApo** [comment] 2019-04-10 13:17
Your request, my command :P

**Closed by GreatApo** 2019-04-10 13:17 UTC
Labels: bug, help wanted
