### ISSUE TITLE
Screenshots issue

### ISSUE THREAD

**Issue by ahsim** [AmazMod/AmazMod#414] opened 2019-02-20 17:25 UTC
Don't work on phone app.

**Comment by 1immortal** [comment] 2019-02-21 16:12
Hi,

Please try the following:
1. open the file explorer from the phone app, and make sure you can see the internal file structure on the watch.
2. go into tweaking and try again.

**Comment by diotto** [comment] 2019-02-21 17:16
One option (probably easier one) is to lock orientation during update using the "Screen.lockOrientation(this)"
Another option is changing android manifest:
https://stackoverflow.com/questions/5913130/dont-reload-application-when-orientation-changes

**Comment by ahsim** [comment] 2019-02-21 20:28
Log with filter amazmod

**Comment by ahsim** [comment] 2019-02-21 20:37
https://drive.google.com/open?id=1xixeJ7FGXA_pKOyPXzRUe_bycKxqPfRZ

**Comment by GreatApo** [comment] 2019-04-05 20:54
@ahsim what is your android version?

**Comment by ahsim** [comment] 2019-04-05 21:25
Android 6.0.1

**Comment by GreatApo** [comment] 2019-04-05 21:28
> Android 6.0.1

And it still doesn't work with the latest update?

Try to run this command from the Tweaking menu:
adb shell screencap

**Comment by ahsim** [comment] 2019-04-05 22:05
I got error "Can't download file" in latest update. But screenshot saved in watch memory in Pictures folder. Same with this adb command

**Comment by fcaronte** [comment] 2019-04-06 04:54
For command was sent but miss something and receive this output
![Screenshot_2019-04-06-06-52-44-948_com edotassi amazmod](https://user-images.githubusercontent.com/26366403/55665040-bfc0b080-5838-11e9-969e-2aff86ffaea0.png)

**Comment by mplx** [comment] 2019-04-06 14:50
I had the same issue some weeks ago, download after screenshot failed but worked via File explorer. Was fixed via rebooting both phone and watch.

**Comment by fcaronte** [comment] 2019-04-06 19:36
What rom are you using? Today I wipe and install stock international firmware for my pace and screenshot start working again! Previous I was on Saratoga ROM based on China firmware and I don't know if problem was ROM or only need a wipe (I forgot to try a wipe only first to change firmware)

**Comment by GreatApo** [comment] 2019-04-06 22:26
Guys, try to run the following commands (from the tweaking menu) and get back to me with which of them work:
`screencap
adb screencap
adb screencap -p`

First command will produce wrong color image.
Keep the screen on when taking pictures (lattest dev build does so automatically)

**Comment by ahsim** [comment] 2019-04-07 08:03
All of this commans works.

**Comment by fcaronte** [comment] 2019-04-07 08:07
What's your watch and firmware\rom version?

**Comment by ahsim** [comment] 2019-04-07 08:52
stratos A1619, global fw 2.3.9.2, amazmod 1.1.5 (service 1890)

**Comment by fcaronte** [comment] 2019-04-07 08:57
But with greatapo command have work and push photo to phone with both tree?

**Comment by ahsim** [comment] 2019-04-07 09:33
I tested only on this release version, I didn't install any dev version. Commands work ok, but button - got error to downloading screenshot, but I check and it appears in watch memory. Maybe it already fixed

**Comment by GreatApo** [comment] 2019-04-07 14:28
These commands and the button to the same thing (they run through the same code) so I am assuming the problem is fixed. I will wait for some more feedback and I will close the issue.

**Comment by fcaronte** [comment] 2019-04-07 14:29
Probably need to push a new beta to have more feedback

**Comment by mplx** [comment] 2019-04-08 07:39
`screencap` - works, upside down, wrong colors
`adb shell screencap` - works, upside down, colors ok
`adb shell screencap -p` - works, upside down, colors ok

`AmazMod 1.1.5` (via Playstore Beta), `Service 1891`, `Verge/A811 fw 3.2.1.0`

**Comment by GreatApo** [comment] 2019-04-19 14:40
So, it seems that the screenshot works in the lattest dev version.
Issue is closed and will re-open if there is a problem again.

**Comment by ahsim** [comment] 2019-04-24 16:37
need to check existing of folder Pictures on the watch

**Comment by GreatApo** [comment] 2019-04-24 16:48
As @ashim said, there seems to be a problem with Pictures folder (or Shreenshots) as he reported that deleting the folder fixes the issues.

**Comment by fcaronte** [comment] 2019-04-24 16:50
no, @GreatApo  is the opposite, if "Picutures" is miss is not work and to fix you need to manually create it

**Comment by fcaronte** [comment] 2019-04-24 17:05
ok fixed :) now if folder is miss he should create

**Comment by fcaronte** [comment] 2019-04-24 20:20
add a fix to check better if model is "verge" (big thanks to @GreatApo ) so now i think we can really close this

**Closed by fcaronte** 2019-04-24 20:20 UTC
Labels: evaluating, help wanted

**Comment by JanHavel** [comment] 2019-05-16 17:20
I have experienced issue "Can download file" when Screenshot button pressed in phone app.
Reboot both devices did not help, but as 1immortal said in 2. post: after accesing screenshot by file explorer in phone app it works. Now it can be auto downloaded when Screenshot button pressed.
