### ISSUE TITLE
Persistent notification

### ISSUE THREAD

**Issue by zeromentu** [AmazMod/AmazMod#332] opened 2018-12-19 22:22 UTC
After three file upload there is a persistent notification

**Comment by lfom** [comment] 2018-12-21 13:57
What phone model and Android version? I tried here, with persistent notification on, and I see a notification about the file transfer, and I can dismiss it manually, so what do you think is the issue actually?

**Comment by zeromentu** [comment] 2018-12-21 14:00
Im using mi 8 with miui10 pie.
The problem is after the file transfer is complete, it says it's 100%, however that notification of can't demiss it, need to reboot to make it disappear

**Comment by lfom** [comment] 2019-02-02 16:10
Any dev seeing this? I have never seen this issue here...
@diotto @GreatApo @fcaronte @1immortal

**Comment by fcaronte** [comment] 2019-02-02 16:17
Usually a hide completely the amazmod and amazfit persistent notification and so I usually not see any notification of transfer, but I try to enable notification and send more file in one time and more file one to one and the notification can be dismissed with a swipe and so for me on android 8 Samsung is work correctly

**Comment by diotto** [comment] 2019-02-02 17:42
Couldn't reproduce here, Stock Android 8 (Moto G4)

**Comment by 1immortal** [comment] 2019-02-05 23:51
Verified on Android 7.1.1, with 1.1.3.1 debug app. Sent the service apk to the watch, file copied successfully, notification regarding![](https://i.imgur.com/beVjmhI.png) the upload remains. Please see attached ss.

**Comment by diotto** [comment] 2019-02-06 09:48
@1immortal did the notification stayed persistent or can you dismiss it?

**Comment by 1immortal** [comment] 2019-02-10 13:06
i could dismiss it, its not there for life.

**Comment by diotto** [comment] 2019-02-11 12:07
> 
> 
> i could dismiss it, its not there for life.

So there is no bug for you. The notification was supposed to stay there (but not persistent).
@zeromentu do you still have this problem with current release (1.1.3) ?

**Comment by zeromentu** [comment] 2019-02-11 15:03
Well it seems to work fine on the current versions, I would consider this as fixed
Thanks for all your help

**Comment by diotto** [comment] 2019-02-11 18:33
So i'm closing the issue :smiley:

**Closed by diotto** 2019-02-11 18:33 UTC
Labels: evaluating, invalid
